spring:
  kafka:
    bootstrap-servers: logistic-kafka:9092
  datasource:
    url: jdbc:postgresql://logistic-db:5432/logistic
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
