spring:
  kafka:
    bootstrap-servers: logistic-kafka:9092
  datasource:
    url: jdbc:postgresql://logistic-db:5432/logistic
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: cargo-contract-service
            client-secret: 35DwiOq67O34g3drYaX9ZJNIBQGzimqg
            client-name: Cargo Contract Service
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/logistic-realm
            token-uri: http://localhost:8080/realms/logistic-realm/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/logistic-realm
