spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    flyway:
      baseline-on-migrate: true
      baseline-version: 1
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
feign:
  okhttp:
    enabled: true