spring:
  datasource:
    url: jdbc:postgresql://logistic-camunda-db:5432/camunda
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
camunda:
  bpm:
    admin-user:
      id: user
      password: user
